started wizard as a new console application with only one command and its own DIC

diff --git a/installer/bin/bootstrap-container b/installer/bin/bootstrap-container
--- a/installer/bin/bootstrap-container
+++ b/installer/bin/bootstrap-container
@@ -10,15 +10,17 @@ chmod +x /installer/bin/* /installer/vendor/bin/* || exit 1
 # Because docker machine stores an absolute path in its config files and
 # we want it to work outside of the installer afterwards.
 # This solution is preferred to editing the json config files after machine creation.
-if ! [ -e "$MACHINE_STORAGE_PATH" ]; then
-	if [ -d "/host/machine" ] && ! [ -d "/host/machine/certs" ]; then
-		>&2 echo "Error: Tried to create a directory named 'machine' on host but it already exists and it is not a valid docker machine storage path."
+if [ "$MACHINE_STORAGE_PATH" != "/host/machine" ]; then
+	if ! [ -e "$MACHINE_STORAGE_PATH" ]; then
+		if [ -d "/host/machine" ] && ! [ -d "/host/machine/certs" ]; then
+			>&2 echo "Error: Tried to create a directory named 'machine' on host but it already exists and it is not a valid docker machine storage path."
+			exit 1
+		fi
+		mkdir -p $(dirname "$MACHINE_STORAGE_PATH")
+		mkdir -p /host/machine/certs
+		ln -sfn /host/machine "${MACHINE_STORAGE_PATH}"
+	elif ! [ -L "$MACHINE_STORAGE_PATH" ]; then
+		>&2 echo "Error: cannot symlink MACHINE_STORAGE_PATH to '$MACHINE_STORAGE_PATH' because it is a real path on installer. Start installer from a different directory on your computer."
 		exit 1
 	fi
-	mkdir -p $(dirname "$MACHINE_STORAGE_PATH")
-	mkdir -p /host/machine/certs
-	ln -sfn /host/machine "${MACHINE_STORAGE_PATH}"
-elif ! [ -L "$MACHINE_STORAGE_PATH" ]; then
-	>&2 echo "Error: cannot symlink MACHINE_STORAGE_PATH to '$MACHINE_STORAGE_PATH' because it is a real path on installer. Start installer from a different directory on your computer."
-	exit 1
 fi
