split basic auth config into username password

diff --git a/installer/bin/create-machine b/installer/bin/create-machine
--- a/installer/bin/create-machine
+++ b/installer/bin/create-machine
@@ -3,11 +3,10 @@
 set -eu
 
 if machine-exists | grep 1 > /dev/null; then
-    >&2 echo "A machine named ${COCOTTE_MACHINE} already exists. Remove it."
+    >&2 echo "Error: a machine named ${COCOTTE_MACHINE} already exists. Remove it or choose a different machine name."
     exit 1;
 fi
 
-### Create cloud vm
 docker-machine -s ${MACHINE_STORAGE_PATH} create \
 	--driver digitalocean \
 	--digitalocean-access-token ${DIGITAL_OCEAN_API_TOKEN} \
